#pragma once

// Finnhub申请类别和代码，免费账户无法申请Premium类的信息
enum {
	__WEBSOCKET__TRADES__ = 1,
	__WEBSOCKET__NEWS__ = __WEBSOCKET__TRADES__ + 1, // Premium

	__STOCK_SYMBOLS__ = 101,
	__COMPANY_PROFILE__ = __STOCK_SYMBOLS__ + 1, //Premium
	__COMPANY_PROFILE_CONCISE__ = __COMPANY_PROFILE__ + 1,
	__COMPANY_EXECTIVE__ = __COMPANY_PROFILE_CONCISE__ + 1, //Premium
	__MARKET_NEWS__ = __COMPANY_EXECTIVE__ + 1,
	__COMPANY_NEWS__ = __MARKET_NEWS__ + 1,
	__PRESS_RELEASE__ = __COMPANY_NEWS__ + 1, //Premium
	__NEWS_SENTIMENT__ = __PRESS_RELEASE__ + 1,
	__PEERS__ = __NEWS_SENTIMENT__ + 1,
	__BASIC_FINANCIALS__ = __PEERS__ + 1,
	__OWNERSHIP__ = __BASIC_FINANCIALS__ + 1, //Premium
	__FUND_OWNERSHIP__ = __OWNERSHIP__ + 1, //Premium
	__INSIDER_TRANSACTION__ = __FUND_OWNERSHIP__ + 1,
	__FINANCIAL__ = __INSIDER_TRANSACTION__ + 1, //Premium
	__FINAICIAL_AS_REPORTED__ = __FINANCIAL__ + 1,
	__REVENUE_BREAKDOWN__ = __FINAICIAL_AS_REPORTED__ + 1,
	__SEC_FILINGS__ = __REVENUE_BREAKDOWN__ + 1,
	__INTERNATIONAL_FILINGS__ = __SEC_FILINGS__ + 1, //Premium
	__SEC_SENTIMENT_ANALYSIS__ = __INTERNATIONAL_FILINGS__ + 1, //Premium
	__SIMILARITY_INDEX__ = __SEC_SENTIMENT_ANALYSIS__ + 1, //Premium
	__IPO_CALENDAR__ = __SIMILARITY_INDEX__ + 1,
	__DIVIDENDS__ = __IPO_CALENDAR__ + 1, //Premium

	__STOCK_ESTIMATES_RECOMMENDATION_TRENDS__ = 201,
	__STOCK_ESTIMATES_PRICE_TARGET__ = __STOCK_ESTIMATES_RECOMMENDATION_TRENDS__ + 1,
	__STOCK_ESTIMATES_UPGRADE_DOWNGRADE__ = __STOCK_ESTIMATES_PRICE_TARGET__ + 1, // Primium
	__STOCK_ESTIMATES_REVENUE_EXTIMATES__ = __STOCK_ESTIMATES_UPGRADE_DOWNGRADE__ + 1, // Premium
	__STOCK_ESTIMATES_EPS_EXTIMATES__ = __STOCK_ESTIMATES_REVENUE_EXTIMATES__ + 1, // Premium
	__STOCK_EXTIMATES_EBITDA_EXTIMATES__ = __STOCK_ESTIMATES_EPS_EXTIMATES__ + 1, // Premium
	__STOCK_EXTIMATES_EBIT_EXTIMATES__ = __STOCK_EXTIMATES_EBITDA_EXTIMATES__ + 1, // Premium
	__STOCK_ESTIMATES_EPS_SURPRISE__ = __STOCK_EXTIMATES_EBIT_EXTIMATES__ + 1,
	__STOCK_ESTIMATES_EARNING_CALENDAR__ = __STOCK_ESTIMATES_EPS_SURPRISE__ + 1,

	__STOCK_PRICE_QUOTE__ = 301, // 实时数据优先级最低
	__STOCK_PRICE_CANDLES__ = __STOCK_PRICE_QUOTE__ + 1, // 历史数据优先级低
	__STOCK_PRICE_TICK_DATA__ = __STOCK_PRICE_CANDLES__ + 1, //Premium
	__STOCK_PRICE_HISTORICAL_NBBO__ = __STOCK_PRICE_TICK_DATA__ + 1, // Premium
	__STOCK_PRICE_LAST_BID_ASK__ = __STOCK_PRICE_HISTORICAL_NBBO__ + 1, //Premium
	__STOCK_PRICE_SPLITS__ = __STOCK_PRICE_LAST_BID_ASK__ + 1, // Premium
	__STOCK_PRICE_DIVIDEND2__ = __STOCK_PRICE_SPLITS__ + 1, // Premium

	__ETFS_INDICES_CONSTITUENTS__ = 401,
	__ETFS_HISTORY_CONSTITUENTS__ = 402, // Premium
	__ETFS_PROFILE__ = 403, // Premiun
	__ETFS_HOLDINGS__ = 404, // Premium
	__ETFS_SECTOR__ = 405, // Premium
	__ETFS_COUNTRY__ = 406, //Premium

	__MUTUAL_FUND_PROFILE__ = 501, // Premium
	__MUTUAL_FUND_HOLDINGS__ = 502, // Premium
	__MUTUAL_FUND_SECTOR__ = 503, // Premium
	__MUTUAL_FUND_COUNTRY__ = 504, // Premium

	__FOREX_EXCHANGE__ = 601,
	__FOREX_SYMBOLS__ = 602,
	__FOREX_CANDLES__ = 603, // 历史数据优先级低 Premium
	__FOREX_ALL_RATES__ = 604, // Premium

	__CRYPTO_EXCHANGE__ = 701,
	__CRYPTO_SYMBOLS__ = 702,
	__CRYPTO_PROFILE__ = 703, // Premium
	__CRYPTO_CANDLES__ = 704,

	__TECHNICAL_ANALYSIS_PATTERN_RECOGNITION__ = 801, // Premium
	__TECHNICAL_ANALYSIS_SURPORT_RESISTANCE__ = 802, // Premium
	__TECHNICAL_ANALYSIS_AGGREGATE_INDICATORS__ = 803, // Premium
	__TECHNICAL_ANALYSIS_TECHNICAL_INDICATORS__ = 804,

	__ALTERNATIVE_DATA_TRANSCRIPT_LIST__ = 901, //Premium
	__ALTERNATIVE_DATA_TRANSCRIPT__, //Premium
	__ALTERNATIVE_DATA_SOCIAL_SETIMENT__,
	__ALTERNATIVE_DATA_INVEST_THEMES__, // Premium
	__ALTERNATIVE_DATA_SUPPLY_CHAIN__, // Premium
	__ALTERNATIVE_DATA_COMPANY_ESG__, // Premium
	__ALTERNATIVE_DATA_EARNING_QUALITY_SCORE__, // Premium
	__ALTERNATIVE_DATA_USPTO_PATENTS__,
	__ALTERNATIVE_DATA_VISA_APPLICATION__, //
	__ALTERNATIVE_DATA_COVID_19__,
	__ALTERNATIVE_DATA_FAD_CALENDAR__,

	__ECONOMIC_COUNTRY_LIST__ = 1001,
	__ECONOMIC_CALENDAR__ = 1002, //Premium
	__ECONOMIC_CODES__ = 1003, //Premium
	__ECONOMIC__ = 1004, //Premium
};
