#pragma once

enum NET_ERROR {
	NET_ERROR_INTERNET_OUT_OF_HANDLES = 12001,
	NET_ERROR_INTERNET_TIMEOUT = 12002,
	NET_ERROR_INTERNET_EXTENDED_ERROR = 12003,
	NET_ERROR_INTERNET_INTERNAL_ERROR = 12004,
	NET_ERROR_INTERNET_INVALID_URL = 12005,
	NET_ERROR_INTERNET_UNRECOGNIZED_SCHEME = 12006,
	NET_ERROR_INTERNET_NAME_NOT_RESOLVED = 12007,
	NET_ERROR_INTERNET_PROTOCOL_NOT_FOUND = 12008,
	NET_ERROR_INTERNET_INVALID_OPTION = 12009,
	NET_ERROR_INTERNET_BAD_OPTION_LENGTH = 12010,
	NET_ERROR_INTERNET_OPTION_NOT_SETTABLE = 12011,
	NET_ERROR_INTERNET_SHUTDOWN = 12012,
	NET_ERROR_INTERNET_INCORRECT_USER_NAME = 12013,
	NET_ERROR_INTERNET_INCORRECT_PASSWORD = 12014,
	NET_ERROR_INTERNET_LOGIN_FAILURE = 12015,
	NET_ERROR_INTERNET_INVALID_OPERATION = 12016,
	NET_ERROR_INTERNET_OPERATION_CANCELLED = 12017,
	NET_ERROR_INTERNET_INCORRECT_HANDLE_TYPE = 12018,
	NET_ERROR_INTERNET_INCORRECT_HANDLE_STATE = 12019,
	NET_ERROR_INTERNET_NOT_PROXY_REQUEST = 12020,
	NET_ERROR_INTERNET_REGISTRY_VALUE_NOT_FOUND = 12021,
	NET_ERROR_INTERNET_BAD_REGISTRY_PARAMETER = 12022,
	NET_ERROR_INTERNET_NO_DIRECT_ACCESS = 12023,
	NET_ERROR_INTERNET_NO_CONTEXT = 12024,
	NET_ERROR_INTERNET_NO_CALLBACK = 12025,
	NET_ERROR_INTERNET_REQUEST_PENDING = 12026,
	NET_ERROR_INTERNET_INCORRECT_FORMAT = 12027,
	NET_ERROR_INTERNET_ITEM_NOT_FOUND = 12028,
	NET_ERROR_INTERNET_CANNOT_CONNECT = 12029,
	NET_ERROR_INTERNET_CONNECTION_ABORTED = 12030,
	NET_ERROR_INTERNET_CONNECTION_RESET = 12031,
	NET_ERROR_INTERNET_FORCE_RETRY = 12032,
	NET_ERROR_INTERNET_INVALID_PROXY_REQUEST = 12033,

	NET_ERROR_INTERNET_HANDLE_EXISTS = 12036,
	NET_ERROR_INTERNET_SEC_CERT_DATE_INVALID = 12037,
	NET_ERROR_INTERNET_SEC_CERT_CN_INVALID = 12038,
	NET_ERROR_INTERNET_HTTP_TO_HTTPS_ON_REDIR = 12039,
	NET_ERROR_INTERNET_HTTPS_TO_HTTP_ON_REDIR = 12040,
	NET_ERROR_INTERNET_MIXED_SECURITY = 12041,
	NET_ERROR_INTERNET_CHG_POST_IS_NON_SECURE = 12042,
	NET_ERROR_INTERNET_POST_IS_NON_SECURE = 12043,

	NET_ERROR_FTP_TRANSFER_IN_PROGRESS = 12110,
	NET_ERROR_FTP_DROPPED = 12111,

	NET_ERROR_GOPHER_PROTOCOL_ERROR = 12130,
	NET_ERROR_GOPHER_NOT_FILE = 12131,
	NET_ERROR_GOPHER_DATA_ERROR = 12132,
	NET_ERROR_GOPHER_END_OF_DATA = 12133,
	NET_ERROR_GOPHER_INVALID_LOCATOR = 12134,
	NET_ERROR_GOPHER_INCORRECT_LOCATOR_TYPE = 12135,
	NET_ERROR_GOPHER_NOT_GOPHER_PLUS = 12136,
	NET_ERROR_GOPHER_ATTRIBUTE_NOT_FOUND = 12137,
	NET_ERROR_GOPHER_UNKNOWN_LOCATOR = 12138,

	NET_ERROR_HTTP_HEADER_NOT_FOUND = 12150,
	NET_ERROR_HTTP_DOWNLEVEL_SERVER = 12151,
	NET_ERROR_HTTP_INVALID_SERVER_RESPONSE = 12152,
	NET_ERROR_HTTP_INVALID_HEADER = 12153,
	NET_ERROR_HTTP_INVALID_QUERY_REQUEST = 12154,
	NET_ERROR_HTTP_HEADER_ALREADY_EXISTS = 12155,
	NET_ERROR_HTTP_REDIRECT_FAILED = 12156
};

extern std::map<long, std::string> gl_mapHTTPStatusCode;
extern std::map<long, std::string> gl_mapNetError;

#include "spdlog/spdlog.h"

using std::shared_ptr;
using std::string;

inline shared_ptr<spdlog::logger> gl_dailyLogger{ nullptr };
inline shared_ptr<spdlog::logger> gl_traceLogger{ nullptr }; // 每日跟踪日志，用于系统调试
inline shared_ptr<spdlog::logger> gl_errorLogger{ nullptr }; // 每日错误日志，用于系统调试
inline shared_ptr<spdlog::logger> gl_dailyWebSocketLogger{ nullptr };
inline shared_ptr<spdlog::logger> gl_dailyWebLogger{ nullptr }; // 网络信息
inline shared_ptr<spdlog::logger> gl_SoftwareDevelopingLogger{ nullptr };

void logInfoDatabaseException(const string& typeName, const string& msg, const sqlpp::mysql::exception& e);
void logWarnDatabaseException(const string& typeName, const string& msg, const sqlpp::mysql::exception& e);
void logErrorDatabaseException(const string& typeName, const string& msg, const sqlpp::mysql::exception& e);
