#include"pch.h"

#include"GeneralCheck.h"

#include"WorldMarket.h"

#include"FinnhubInquiryType.h"

using namespace testing;

#ifdef _DEBUG
#define new DEBUG_NEW
#undef THIS_FILE
static char THIS_FILE[] = __FILE__;
#endif

namespace StockAnalysisTest {
	TEST(FinnhubInquiryTypeTest, Test) {
		EXPECT_EQ(_WEBSOCKET_TRADES_, 1);
		EXPECT_EQ(_WEBSOCKET_NEWS_, _WEBSOCKET_TRADES_ + 1);

		EXPECT_EQ(_SYMBOL_LOOKUP_, _WEBSOCKET_TRADES_ + 100);
		EXPECT_EQ(_STOCK_SYMBOLS_, _SYMBOL_LOOKUP_ + 1);
		EXPECT_EQ(_COMPANY_PROFILE_, _STOCK_SYMBOLS_ + 1);
		EXPECT_EQ(_COMPANY_PROFILE_CONCISE_, _COMPANY_PROFILE_ + 1);
		EXPECT_EQ(_COMPANY_EXECTIVE_, _COMPANY_PROFILE_CONCISE_ + 1);
		EXPECT_EQ(_MARKET_NEWS_, _COMPANY_EXECTIVE_ + 1);
		EXPECT_EQ(_COMPANY_NEWS_, _MARKET_NEWS_ + 1);
		EXPECT_EQ(_PRESS_RELEASE_, _COMPANY_NEWS_ + 1);
		EXPECT_EQ(_NEWS_SENTIMENT_, _PRESS_RELEASE_ + 1);
		EXPECT_EQ(_PEERS_, _NEWS_SENTIMENT_ + 1);
		EXPECT_EQ(_BASIC_FINANCIALS_, _PEERS_ + 1);
		EXPECT_EQ(_OWNERSHIP_, _BASIC_FINANCIALS_ + 1);
		EXPECT_EQ(_FUND_OWNERSHIP_, _OWNERSHIP_ + 1);
		EXPECT_EQ(_INSIDER_TRANSACTION_, _FUND_OWNERSHIP_ + 1);
		EXPECT_EQ(_INSIDER_SENTIMENT_, _INSIDER_TRANSACTION_ + 1);
		EXPECT_EQ(_FINANCIAL_, _INSIDER_SENTIMENT_ + 1);
		EXPECT_EQ(_FINANCIAL_AS_REPORTED_, _FINANCIAL_ + 1);
		EXPECT_EQ(_REVENUE_BREAKDOWN_, _FINANCIAL_AS_REPORTED_ + 1);
		EXPECT_EQ(_SEC_FILINGS_, _REVENUE_BREAKDOWN_ + 1);
		EXPECT_EQ(_INTERNATIONAL_FILINGS_, _SEC_FILINGS_ + 1);
		EXPECT_EQ(_SEC_SENTIMENT_ANALYSIS_, _INTERNATIONAL_FILINGS_ + 1);
		EXPECT_EQ(_SIMILARITY_INDEX_, _SEC_SENTIMENT_ANALYSIS_ + 1);
		EXPECT_EQ(_IPO_CALENDAR_, _SIMILARITY_INDEX_ + 1);
		EXPECT_EQ(_DIVIDENDS_, _IPO_CALENDAR_ + 1);

		EXPECT_EQ(_STOCK_ESTIMATES_RECOMMENDATION_TRENDS_, _SYMBOL_LOOKUP_ + 100);
		EXPECT_EQ(_STOCK_ESTIMATES_PRICE_TARGET_, _STOCK_ESTIMATES_RECOMMENDATION_TRENDS_ + 1);
		EXPECT_EQ(_STOCK_ESTIMATES_UPGRADE_DOWNGRADE_, _STOCK_ESTIMATES_PRICE_TARGET_ + 1);
		EXPECT_EQ(_STOCK_ESTIMATES_REVENUE_EXTIMATES_, _STOCK_ESTIMATES_UPGRADE_DOWNGRADE_ + 1);
		EXPECT_EQ(_STOCK_ESTIMATES_EPS_EXTIMATES_, _STOCK_ESTIMATES_REVENUE_EXTIMATES_ + 1);
		EXPECT_EQ(_STOCK_EXTIMATES_EBITDA_EXTIMATES_, _STOCK_ESTIMATES_EPS_EXTIMATES_ + 1);
		EXPECT_EQ(_STOCK_EXTIMATES_EBIT_EXTIMATES_, _STOCK_EXTIMATES_EBITDA_EXTIMATES_ + 1);
		EXPECT_EQ(_STOCK_ESTIMATES_EPS_SURPRISE_, _STOCK_EXTIMATES_EBIT_EXTIMATES_ + 1);
		EXPECT_EQ(_STOCK_ESTIMATES_EARNING_CALENDAR_, _STOCK_ESTIMATES_EPS_SURPRISE_ + 1);

		EXPECT_EQ(_STOCK_PRICE_QUOTE_, _STOCK_ESTIMATES_RECOMMENDATION_TRENDS_ + 100);
		EXPECT_EQ(_STOCK_PRICE_CANDLES_, _STOCK_PRICE_QUOTE_ + 1);
		EXPECT_EQ(_STOCK_PRICE_TICK_DATA_, _STOCK_PRICE_CANDLES_ + 1);
		EXPECT_EQ(_STOCK_PRICE_HISTORICAL_NBBO_, _STOCK_PRICE_TICK_DATA_ + 1);
		EXPECT_EQ(_STOCK_PRICE_LAST_BID_ASK_, _STOCK_PRICE_HISTORICAL_NBBO_ + 1);
		EXPECT_EQ(_STOCK_PRICE_SPLITS_, _STOCK_PRICE_LAST_BID_ASK_ + 1);
		EXPECT_EQ(_STOCK_PRICE_DIVIDEND2_, _STOCK_PRICE_SPLITS_ + 1);

		EXPECT_EQ(_ETFS_INDICES_CONSTITUENTS_, _STOCK_PRICE_QUOTE_ + 100);
		EXPECT_EQ(_ETFS_HISTORY_CONSTITUENTS_, _ETFS_INDICES_CONSTITUENTS_ + 1);
		EXPECT_EQ(_ETFS_PROFILE_, _ETFS_HISTORY_CONSTITUENTS_ + 1);
		EXPECT_EQ(_ETFS_HOLDINGS_, _ETFS_PROFILE_ + 1);
		EXPECT_EQ(_ETFS_SECTOR_, _ETFS_HOLDINGS_ + 1);
		EXPECT_EQ(_ETFS_COUNTRY_, _ETFS_SECTOR_ + 1);

		EXPECT_EQ(_MUTUAL_FUND_PROFILE_, _ETFS_INDICES_CONSTITUENTS_ + 100);
		EXPECT_EQ(_MUTUAL_FUND_HOLDINGS_, _MUTUAL_FUND_PROFILE_ + 1);
		EXPECT_EQ(_MUTUAL_FUND_SECTOR_, _MUTUAL_FUND_HOLDINGS_ + 1);
		EXPECT_EQ(_MUTUAL_FUND_COUNTRY_, _MUTUAL_FUND_SECTOR_ + 1);

		EXPECT_EQ(_BOND_PROFILE_, _MUTUAL_FUND_PROFILE_ + 100);
		EXPECT_EQ(_BOND_PRICE_, _BOND_PROFILE_ + 1);

		EXPECT_EQ(_FOREX_EXCHANGE_, _BOND_PROFILE_ + 100);
		EXPECT_EQ(_FOREX_SYMBOLS_, _FOREX_EXCHANGE_ + 1);
		EXPECT_EQ(_FOREX_CANDLES_, _FOREX_SYMBOLS_ + 1);
		EXPECT_EQ(_FOREX_ALL_RATES_, _FOREX_CANDLES_ + 1);

		EXPECT_EQ(_CRYPTO_EXCHANGE_, _FOREX_EXCHANGE_ + 100);
		EXPECT_EQ(_CRYPTO_SYMBOLS_, _CRYPTO_EXCHANGE_ + 1);
		EXPECT_EQ(_CRYPTO_PROFILE_, _CRYPTO_SYMBOLS_ + 1);
		EXPECT_EQ(_CRYPTO_CANDLES_, _CRYPTO_PROFILE_ + 1);

		EXPECT_EQ(_TECHNICAL_ANALYSIS_PATTERN_RECOGNITION_, _CRYPTO_EXCHANGE_ + 100);
		EXPECT_EQ(_TECHNICAL_ANALYSIS_SURPORT_RESISTANCE_, _TECHNICAL_ANALYSIS_PATTERN_RECOGNITION_ + 1);
		EXPECT_EQ(_TECHNICAL_ANALYSIS_AGGREGATE_INDICATORS_, _TECHNICAL_ANALYSIS_SURPORT_RESISTANCE_ + 1);
		EXPECT_EQ(_TECHNICAL_ANALYSIS_TECHNICAL_INDICATORS_, _TECHNICAL_ANALYSIS_AGGREGATE_INDICATORS_ + 1);

		EXPECT_EQ(_ALTERNATIVE_DATA_TRANSCRIPT_LIST_, _TECHNICAL_ANALYSIS_PATTERN_RECOGNITION_ + 100);
		EXPECT_EQ(_ALTERNATIVE_DATA_TRANSCRIPT_, _ALTERNATIVE_DATA_TRANSCRIPT_LIST_ + 1);
		EXPECT_EQ(_ALTERNATIVE_DATA_SOCIAL_SETIMENT_, _ALTERNATIVE_DATA_TRANSCRIPT_ + 1);
		EXPECT_EQ(_ALTERNATIVE_DATA_INVEST_THEMES_, _ALTERNATIVE_DATA_SOCIAL_SETIMENT_ + 1);
		EXPECT_EQ(_ALTERNATIVE_DATA_SUPPLY_CHAIN_, _ALTERNATIVE_DATA_INVEST_THEMES_ + 1);
		EXPECT_EQ(_ALTERNATIVE_DATA_COMPANY_ESG_, _ALTERNATIVE_DATA_SUPPLY_CHAIN_ + 1);
		EXPECT_EQ(_ALTERNATIVE_DATA_EARNING_QUALITY_SCORE_, _ALTERNATIVE_DATA_COMPANY_ESG_ + 1);
		EXPECT_EQ(_ALTERNATIVE_DATA_USPTO_PATENTS_, _ALTERNATIVE_DATA_EARNING_QUALITY_SCORE_ + 1);
		EXPECT_EQ(_ALTERNATIVE_DATA_VISA_APPLICATION_, _ALTERNATIVE_DATA_USPTO_PATENTS_ + 1);
		EXPECT_EQ(_ALTERNATIVE_DATA_COVID_19_, _ALTERNATIVE_DATA_VISA_APPLICATION_ + 1);
		EXPECT_EQ(_ALTERNATIVE_DATA_FDA_CALENDAR_, _ALTERNATIVE_DATA_COVID_19_ + 1);

		EXPECT_EQ(_ECONOMIC_COUNTRY_LIST_, _ALTERNATIVE_DATA_TRANSCRIPT_LIST_ + 100);
		EXPECT_EQ(_ECONOMIC_CALENDAR_, _ECONOMIC_COUNTRY_LIST_ + 1);
		EXPECT_EQ(_ECONOMIC_CODES_, _ECONOMIC_CALENDAR_ + 1);
		EXPECT_EQ(_ECONOMIC_ECONOMIC_, _ECONOMIC_CODES_ + 1);
	}
}