#include"pch.h"

#include"GeneralCheck.h"

#include"WorldMarket.h"

#include"FinnhubInquiryType.h"

using namespace testing;

#ifdef _DEBUG
#define new DEBUG_NEW
#undef THIS_FILE
static char THIS_FILE[] = __FILE__;
#endif

namespace StockAnalysisTest {
	TEST(FinnhubInquiryTypeTest, Test) {
		EXPECT_EQ(__WEBSOCKET__TRADES__, 1);
		EXPECT_EQ(__WEBSOCKET__NEWS__, __WEBSOCKET__TRADES__ + 1);

		EXPECT_EQ(__STOCK_SYMBOLS__, __WEBSOCKET__TRADES__ + 100);
		EXPECT_EQ(__COMPANY_PROFILE__, __STOCK_SYMBOLS__ + 1);
		EXPECT_EQ(__COMPANY_PROFILE_CONCISE__, __COMPANY_PROFILE__ + 1);
		EXPECT_EQ(__COMPANY_EXECTIVE__, __COMPANY_PROFILE_CONCISE__ + 1);
		EXPECT_EQ(__MARKET_NEWS__, __COMPANY_EXECTIVE__ + 1);
		EXPECT_EQ(__COMPANY_NEWS__, __MARKET_NEWS__ + 1);
		EXPECT_EQ(__PRESS_RELEASE__, __COMPANY_NEWS__ + 1);
		EXPECT_EQ(__NEWS_SENTIMENT__, __PRESS_RELEASE__ + 1);
		EXPECT_EQ(__PEERS__, __NEWS_SENTIMENT__ + 1);
		EXPECT_EQ(__BASIC_FINANCIALS__, __PEERS__ + 1);
		EXPECT_EQ(__OWNERSHIP__, __BASIC_FINANCIALS__ + 1);
		EXPECT_EQ(__FUND_OWNERSHIP__, __OWNERSHIP__ + 1);
		EXPECT_EQ(__INSIDER_TRANSACTION__, __FUND_OWNERSHIP__ + 1);
		EXPECT_EQ(__INSIDER_SENTIMENT__, __INSIDER_TRANSACTION__ + 1);
		EXPECT_EQ(__FINANCIAL__, __INSIDER_SENTIMENT__ + 1);
		EXPECT_EQ(__FINAICIAL_AS_REPORTED__, __FINANCIAL__ + 1);
		EXPECT_EQ(__REVENUE_BREAKDOWN__, __FINAICIAL_AS_REPORTED__ + 1);
		EXPECT_EQ(__SEC_FILINGS__, __REVENUE_BREAKDOWN__ + 1);
		EXPECT_EQ(__INTERNATIONAL_FILINGS__, __SEC_FILINGS__ + 1);
		EXPECT_EQ(__SEC_SENTIMENT_ANALYSIS__, __INTERNATIONAL_FILINGS__ + 1);
		EXPECT_EQ(__SIMILARITY_INDEX__, __SEC_SENTIMENT_ANALYSIS__ + 1);
		EXPECT_EQ(__IPO_CALENDAR__, __SIMILARITY_INDEX__ + 1);
		EXPECT_EQ(__DIVIDENDS__, __IPO_CALENDAR__ + 1);

		EXPECT_EQ(__STOCK_ESTIMATES_RECOMMENDATION_TRENDS__, __STOCK_SYMBOLS__ + 100);
		EXPECT_EQ(__STOCK_ESTIMATES_PRICE_TARGET__, __STOCK_ESTIMATES_RECOMMENDATION_TRENDS__ + 1);
		EXPECT_EQ(__STOCK_ESTIMATES_UPGRADE_DOWNGRADE__, __STOCK_ESTIMATES_PRICE_TARGET__ + 1);
		EXPECT_EQ(__STOCK_ESTIMATES_REVENUE_EXTIMATES__, __STOCK_ESTIMATES_UPGRADE_DOWNGRADE__ + 1);
		EXPECT_EQ(__STOCK_ESTIMATES_EPS_EXTIMATES__, __STOCK_ESTIMATES_REVENUE_EXTIMATES__ + 1);
		EXPECT_EQ(__STOCK_EXTIMATES_EBITDA_EXTIMATES__, __STOCK_ESTIMATES_EPS_EXTIMATES__ + 1);
		EXPECT_EQ(__STOCK_EXTIMATES_EBIT_EXTIMATES__, __STOCK_EXTIMATES_EBITDA_EXTIMATES__ + 1);
		EXPECT_EQ(__STOCK_ESTIMATES_EPS_SURPRISE__, __STOCK_EXTIMATES_EBIT_EXTIMATES__ + 1);
		EXPECT_EQ(__STOCK_ESTIMATES_EARNING_CALENDAR__, __STOCK_ESTIMATES_EPS_SURPRISE__ + 1);

		EXPECT_EQ(__STOCK_PRICE_QUOTE__, __STOCK_ESTIMATES_RECOMMENDATION_TRENDS__ + 100);
		EXPECT_EQ(__STOCK_PRICE_CANDLES__, __STOCK_PRICE_QUOTE__ + 1);
		EXPECT_EQ(__STOCK_PRICE_TICK_DATA__, __STOCK_PRICE_CANDLES__ + 1);
		EXPECT_EQ(__STOCK_PRICE_HISTORICAL_NBBO__, __STOCK_PRICE_TICK_DATA__ + 1);
		EXPECT_EQ(__STOCK_PRICE_LAST_BID_ASK__, __STOCK_PRICE_HISTORICAL_NBBO__ + 1);
		EXPECT_EQ(__STOCK_PRICE_SPLITS__, __STOCK_PRICE_LAST_BID_ASK__ + 1);
		EXPECT_EQ(__STOCK_PRICE_DIVIDEND2__, __STOCK_PRICE_SPLITS__ + 1);

		EXPECT_EQ(__ETFS_INDICES_CONSTITUENTS__, __STOCK_PRICE_QUOTE__ + 100);
		EXPECT_EQ(__ETFS_HISTORY_CONSTITUENTS__, __ETFS_INDICES_CONSTITUENTS__ + 1);
		EXPECT_EQ(__ETFS_PROFILE__, __ETFS_HISTORY_CONSTITUENTS__ + 1);
		EXPECT_EQ(__ETFS_HOLDINGS__, __ETFS_PROFILE__ + 1);
		EXPECT_EQ(__ETFS_SECTOR__, __ETFS_HOLDINGS__ + 1);
		EXPECT_EQ(__ETFS_COUNTRY__, __ETFS_SECTOR__ + 1);

		EXPECT_EQ(__MUTUAL_FUND_PROFILE__, __ETFS_INDICES_CONSTITUENTS__ + 100);
		EXPECT_EQ(__MUTUAL_FUND_HOLDINGS__, __MUTUAL_FUND_PROFILE__ + 1);
		EXPECT_EQ(__MUTUAL_FUND_SECTOR__, __MUTUAL_FUND_HOLDINGS__ + 1);
		EXPECT_EQ(__MUTUAL_FUND_COUNTRY__, __MUTUAL_FUND_SECTOR__ + 1);

		EXPECT_EQ(__BOND_PROFILE__, __MUTUAL_FUND_PROFILE__ + 100);
		EXPECT_EQ(__BOND_PRICE__, __BOND_PROFILE__ + 1);

		EXPECT_EQ(__FOREX_EXCHANGE__, __BOND_PROFILE__ + 100);
		EXPECT_EQ(__FOREX_SYMBOLS__, __FOREX_EXCHANGE__ + 1);
		EXPECT_EQ(__FOREX_CANDLES__, __FOREX_SYMBOLS__ + 1);
		EXPECT_EQ(__FOREX_ALL_RATES__, __FOREX_CANDLES__ + 1);

		EXPECT_EQ(__CRYPTO_EXCHANGE__, __FOREX_EXCHANGE__ + 100);
		EXPECT_EQ(__CRYPTO_SYMBOLS__, __CRYPTO_EXCHANGE__ + 1);
		EXPECT_EQ(__CRYPTO_PROFILE__, __CRYPTO_SYMBOLS__ + 1);
		EXPECT_EQ(__CRYPTO_CANDLES__, __CRYPTO_PROFILE__ + 1);

		EXPECT_EQ(__TECHNICAL_ANALYSIS_PATTERN_RECOGNITION__, __CRYPTO_EXCHANGE__ + 100);
		EXPECT_EQ(__TECHNICAL_ANALYSIS_SURPORT_RESISTANCE__, __TECHNICAL_ANALYSIS_PATTERN_RECOGNITION__ + 1);
		EXPECT_EQ(__TECHNICAL_ANALYSIS_AGGREGATE_INDICATORS__, __TECHNICAL_ANALYSIS_SURPORT_RESISTANCE__ + 1);
		EXPECT_EQ(__TECHNICAL_ANALYSIS_TECHNICAL_INDICATORS__, __TECHNICAL_ANALYSIS_AGGREGATE_INDICATORS__ + 1);

		EXPECT_EQ(__ALTERNATIVE_DATA_TRANSCRIPT_LIST__, __TECHNICAL_ANALYSIS_PATTERN_RECOGNITION__ + 100);
		EXPECT_EQ(__ALTERNATIVE_DATA_TRANSCRIPT__, __ALTERNATIVE_DATA_TRANSCRIPT_LIST__ + 1);
		EXPECT_EQ(__ALTERNATIVE_DATA_SOCIAL_SETIMENT__, __ALTERNATIVE_DATA_TRANSCRIPT__ + 1);
		EXPECT_EQ(__ALTERNATIVE_DATA_INVEST_THEMES__, __ALTERNATIVE_DATA_SOCIAL_SETIMENT__ + 1);
		EXPECT_EQ(__ALTERNATIVE_DATA_SUPPLY_CHAIN__, __ALTERNATIVE_DATA_INVEST_THEMES__ + 1);
		EXPECT_EQ(__ALTERNATIVE_DATA_COMPANY_ESG__, __ALTERNATIVE_DATA_SUPPLY_CHAIN__ + 1);
		EXPECT_EQ(__ALTERNATIVE_DATA_EARNING_QUALITY_SCORE__, __ALTERNATIVE_DATA_COMPANY_ESG__ + 1);
		EXPECT_EQ(__ALTERNATIVE_DATA_USPTO_PATENTS__, __ALTERNATIVE_DATA_EARNING_QUALITY_SCORE__ + 1);
		EXPECT_EQ(__ALTERNATIVE_DATA_VISA_APPLICATION__, __ALTERNATIVE_DATA_USPTO_PATENTS__ + 1);
		EXPECT_EQ(__ALTERNATIVE_DATA_COVID_19__, __ALTERNATIVE_DATA_VISA_APPLICATION__ + 1);
		EXPECT_EQ(__ALTERNATIVE_DATA_FAD_CALENDAR__, __ALTERNATIVE_DATA_COVID_19__ + 1);

		EXPECT_EQ(__ECONOMIC_COUNTRY_LIST__, __ALTERNATIVE_DATA_TRANSCRIPT_LIST__ + 100);
		EXPECT_EQ(__ECONOMIC_CALENDAR__, __ECONOMIC_COUNTRY_LIST__ + 1);
		EXPECT_EQ(__ECONOMIC_CODES__, __ECONOMIC_CALENDAR__ + 1);
		EXPECT_EQ(__ECONOMIC_ECONOMIC__, __ECONOMIC_CODES__ + 1);
	}
}