#pragma once

// Finnhub申请类别和代码，免费账户无法申请Premium类的信息
enum {
	// Web Socket
	_WEBSOCKET_TRADES_ = 1,
	_WEBSOCKET_NEWS_ = _WEBSOCKET_TRADES_ + 1, // Premium

	// Stock Fundamentals
	_SYMBOL_LOOKUP_ = _WEBSOCKET_TRADES_ + 100,
	_STOCK_SYMBOLS_ = _SYMBOL_LOOKUP_ + 1,
	_COMPANY_PROFILE_ = _STOCK_SYMBOLS_ + 1, //Premium
	_COMPANY_PROFILE_CONCISE_ = _COMPANY_PROFILE_ + 1,
	_COMPANY_EXECTIVE_ = _COMPANY_PROFILE_CONCISE_ + 1, //Premium
	_MARKET_NEWS_ = _COMPANY_EXECTIVE_ + 1,
	_COMPANY_NEWS_ = _MARKET_NEWS_ + 1,
	_PRESS_RELEASE_ = _COMPANY_NEWS_ + 1, //Premium
	_NEWS_SENTIMENT_ = _PRESS_RELEASE_ + 1,
	_PEERS_ = _NEWS_SENTIMENT_ + 1,
	_BASIC_FINANCIALS_ = _PEERS_ + 1,
	_OWNERSHIP_ = _BASIC_FINANCIALS_ + 1, //Premium
	_FUND_OWNERSHIP_ = _OWNERSHIP_ + 1, //Premium
	_INSIDER_TRANSACTION_ = _FUND_OWNERSHIP_ + 1,
	_INSIDER_SENTIMENT_ = _INSIDER_TRANSACTION_ + 1,
	_FINANCIAL_ = _INSIDER_SENTIMENT_ + 1, //Premium
	_FINAICIAL_AS_REPORTED_ = _FINANCIAL_ + 1,
	_REVENUE_BREAKDOWN_ = _FINAICIAL_AS_REPORTED_ + 1,
	_SEC_FILINGS_ = _REVENUE_BREAKDOWN_ + 1,
	_INTERNATIONAL_FILINGS_ = _SEC_FILINGS_ + 1, //Premium
	_SEC_SENTIMENT_ANALYSIS_ = _INTERNATIONAL_FILINGS_ + 1, //Premium
	_SIMILARITY_INDEX_ = _SEC_SENTIMENT_ANALYSIS_ + 1, //Premium
	_IPO_CALENDAR_ = _SIMILARITY_INDEX_ + 1,
	_DIVIDENDS_ = _IPO_CALENDAR_ + 1, //Premium

	// Stock Estimates
	_STOCK_ESTIMATES_RECOMMENDATION_TRENDS_ = _SYMBOL_LOOKUP_ + 100,
	_STOCK_ESTIMATES_PRICE_TARGET_ = _STOCK_ESTIMATES_RECOMMENDATION_TRENDS_ + 1, // Primium
	_STOCK_ESTIMATES_UPGRADE_DOWNGRADE_ = _STOCK_ESTIMATES_PRICE_TARGET_ + 1, // Premium
	_STOCK_ESTIMATES_REVENUE_EXTIMATES_ = _STOCK_ESTIMATES_UPGRADE_DOWNGRADE_ + 1, // Premium
	_STOCK_ESTIMATES_EPS_EXTIMATES_ = _STOCK_ESTIMATES_REVENUE_EXTIMATES_ + 1, // Premium
	_STOCK_EXTIMATES_EBITDA_EXTIMATES_ = _STOCK_ESTIMATES_EPS_EXTIMATES_ + 1, // Premium
	_STOCK_EXTIMATES_EBIT_EXTIMATES_ = _STOCK_EXTIMATES_EBITDA_EXTIMATES_ + 1,
	_STOCK_ESTIMATES_EPS_SURPRISE_ = _STOCK_EXTIMATES_EBIT_EXTIMATES_ + 1,
	_STOCK_ESTIMATES_EARNING_CALENDAR_ = _STOCK_ESTIMATES_EPS_SURPRISE_ + 1,

	// Stock Price
	_STOCK_PRICE_QUOTE_ = _STOCK_ESTIMATES_RECOMMENDATION_TRENDS_ + 100, // 实时数据优先级最低
	_STOCK_PRICE_CANDLES_ = _STOCK_PRICE_QUOTE_ + 1, // 历史数据优先级低
	_STOCK_PRICE_TICK_DATA_ = _STOCK_PRICE_CANDLES_ + 1, // Premium
	_STOCK_PRICE_HISTORICAL_NBBO_ = _STOCK_PRICE_TICK_DATA_ + 1, //Premium
	_STOCK_PRICE_LAST_BID_ASK_ = _STOCK_PRICE_HISTORICAL_NBBO_ + 1, // Premium
	_STOCK_PRICE_SPLITS_ = _STOCK_PRICE_LAST_BID_ASK_ + 1, // Premium
	_STOCK_PRICE_DIVIDEND2_ = _STOCK_PRICE_SPLITS_ + 1, //Premium

	// ETF & Indices
	_ETFS_INDICES_CONSTITUENTS_ = _STOCK_PRICE_QUOTE_ + 100,
	_ETFS_HISTORY_CONSTITUENTS_ = _ETFS_INDICES_CONSTITUENTS_ + 1, // Premium
	_ETFS_PROFILE_ = _ETFS_HISTORY_CONSTITUENTS_ + 1, // Premiun
	_ETFS_HOLDINGS_ = _ETFS_PROFILE_ + 1, // Premium
	_ETFS_SECTOR_ = _ETFS_HOLDINGS_ + 1, // Premium
	_ETFS_COUNTRY_ = _ETFS_SECTOR_ + 1, //Premium

	// Mutual funds
	_MUTUAL_FUND_PROFILE_ = _ETFS_INDICES_CONSTITUENTS_ + 100, // Premium
	_MUTUAL_FUND_HOLDINGS_ = _MUTUAL_FUND_PROFILE_ + 1, // Premium
	_MUTUAL_FUND_SECTOR_ = _MUTUAL_FUND_HOLDINGS_ + 1, // Premium
	_MUTUAL_FUND_COUNTRY_ = _MUTUAL_FUND_SECTOR_ + 1, // Premium

	// Bonds
	_BOND_PROFILE_ = _MUTUAL_FUND_PROFILE_ + 100, // Premium
	_BOND_PRICE_ = _BOND_PROFILE_ + 1, // Premium

	// Forex
	_FOREX_EXCHANGE_ = _BOND_PROFILE_ + 100,
	_FOREX_SYMBOLS_ = _FOREX_EXCHANGE_ + 1,
	_FOREX_CANDLES_ = _FOREX_SYMBOLS_ + 1, // 历史数据优先级低 Premium
	_FOREX_ALL_RATES_ = _FOREX_CANDLES_ + 1, // Premium

	// Crypto
	_CRYPTO_EXCHANGE_ = _FOREX_EXCHANGE_ + 100,
	_CRYPTO_SYMBOLS_ = _CRYPTO_EXCHANGE_ + 1,
	_CRYPTO_PROFILE_ = _CRYPTO_SYMBOLS_ + 1, // Premium
	_CRYPTO_CANDLES_ = _CRYPTO_PROFILE_ + 1,

	// Technical Analysis
	_TECHNICAL_ANALYSIS_PATTERN_RECOGNITION_ = _CRYPTO_EXCHANGE_ + 100, // Premium
	_TECHNICAL_ANALYSIS_SURPORT_RESISTANCE_ = _TECHNICAL_ANALYSIS_PATTERN_RECOGNITION_ + 1, // Premium
	_TECHNICAL_ANALYSIS_AGGREGATE_INDICATORS_ = _TECHNICAL_ANALYSIS_SURPORT_RESISTANCE_ + 1, // Premium
	_TECHNICAL_ANALYSIS_TECHNICAL_INDICATORS_ = _TECHNICAL_ANALYSIS_AGGREGATE_INDICATORS_ + 1,

	// Alternative Data
	_ALTERNATIVE_DATA_TRANSCRIPT_LIST_ = _TECHNICAL_ANALYSIS_PATTERN_RECOGNITION_ + 100, //Premium
	_ALTERNATIVE_DATA_TRANSCRIPT_ = _ALTERNATIVE_DATA_TRANSCRIPT_LIST_ + 1, //Premium
	_ALTERNATIVE_DATA_SOCIAL_SETIMENT_ = _ALTERNATIVE_DATA_TRANSCRIPT_ + 1,
	_ALTERNATIVE_DATA_INVEST_THEMES_ = _ALTERNATIVE_DATA_SOCIAL_SETIMENT_ + 1, // Premium
	_ALTERNATIVE_DATA_SUPPLY_CHAIN_ = _ALTERNATIVE_DATA_INVEST_THEMES_ + 1, // Premium
	_ALTERNATIVE_DATA_COMPANY_ESG_ = _ALTERNATIVE_DATA_SUPPLY_CHAIN_ + 1, // Premium
	_ALTERNATIVE_DATA_EARNING_QUALITY_SCORE_ = _ALTERNATIVE_DATA_COMPANY_ESG_ + 1, // Premium
	_ALTERNATIVE_DATA_USPTO_PATENTS_ = _ALTERNATIVE_DATA_EARNING_QUALITY_SCORE_ + 1,
	_ALTERNATIVE_DATA_VISA_APPLICATION_ = _ALTERNATIVE_DATA_USPTO_PATENTS_ + 1,
	//
	_ALTERNATIVE_DATA_COVID_19_ = _ALTERNATIVE_DATA_VISA_APPLICATION_ + 1,
	_ALTERNATIVE_DATA_FDA_CALENDAR_ = _ALTERNATIVE_DATA_COVID_19_ + 1,

	// Econimic
	_ECONOMIC_COUNTRY_LIST_ = _ALTERNATIVE_DATA_TRANSCRIPT_LIST_ + 100,
	_ECONOMIC_CALENDAR_ = _ECONOMIC_COUNTRY_LIST_ + 1, //Premium
	_ECONOMIC_CODES_ = _ECONOMIC_CALENDAR_ + 1, //Premium
	_ECONOMIC_ECONOMIC_ = _ECONOMIC_CODES_ + 1,
	//Premium
};
